//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamSystem.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntryStock()
        {
            this.Log = new HashSet<Log>();
        }
    
        public int IdStock { get; set; }
        public System.DateTime FabicationDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string ProductBatch { get; set; }
        public int Amount { get; set; }
        public int ProductId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Log { get; set; }
        public virtual Product Product { get; set; }
    }
}
