//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamSystem.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int IdLog { get; set; }
        public string Old { get; set; }
        public string New { get; set; }
        public int Who { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UnitMeasureId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> CreditCardId { get; set; }
        public Nullable<int> EntryStockId { get; set; }
        public Nullable<int> DebitCardId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
        public virtual CreditCard CreditCard { get; set; }
        public virtual DebitCard DebitCard { get; set; }
        public virtual EntryStock EntryStock { get; set; }
        public virtual Office Office { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Product Product { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual UnitMeasure UnitMeasure { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual Worker Worker1 { get; set; }
    }
}
