//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamSystem.DBContext
{
    using System;
    
    public enum Perimission : int
    {
        SuperAdmin = 1,
        Admin = 2,
        Supervisor = 3,
        Seller = 4
    }
}
