//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamSystem.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int IdPhone { get; set; }
        public int TypePhone { get; set; }
        public string DDD { get; set; }
        public string Number { get; set; }
        public int Status { get; set; }
        public int WorkerId { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
