//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamSystem.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Log = new HashSet<Log>();
            this.Log1 = new HashSet<Log>();
            this.Phone = new HashSet<Phone>();
            this.Sale = new HashSet<Sale>();
        }
    
        public int IdWorker { get; set; }
        public string NameWorker { get; set; }
        public System.DateTime Birth { get; set; }
        public System.DateTime Admission { get; set; }
        public decimal Salary { get; set; }
        public int AddressId { get; set; }
        public int OfficeId { get; set; }
        public int CompanyId { get; set; }
        public bool HaveLogin { get; set; }
        public Nullable<Perimission> Permission { get; set; }
        public string LoginUser { get; set; }
        public string PasswordUser { get; set; }
        public Status Status { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Log1 { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phone> Phone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
